# Generated by Django 2.1.1 on 2018-09-12 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news_mapper_web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', news_mapper_web.models.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default=None, max_length=75, null=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('article_url', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=2500)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_last_edit', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='NewsQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('headlines', 'Headlines'), ('all', 'All')], default='headlines', max_length=50)),
                ('data', models.CharField(blank=True, max_length=200000, null=True)),
                ('choropleth', models.FileField(blank=True, default=None, null=True, upload_to='dociments/')),
                ('argument', models.CharField(max_length=500)),
                ('date_range_start', models.DateField(blank=True, default=None, null=True)),
                ('date_range_end', models.DateField(blank=True, default=None, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=2500)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('date_last_edit', models.DateTimeField(default=None)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news_mapper_web.NewsQuery')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('country_alpha_code', models.CharField(blank=True, max_length=3, null=True)),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('api_id', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('category', models.CharField(blank=True, choices=[('businiess', 'Business'), ('entertainment', 'Entertainment'), ('general', 'General'), ('health', 'Health'), ('science', 'Science'), ('sports', 'Sports'), ('technology', 'Technology')], default=None, max_length=50, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news_mapper_web.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_mapper_web.NewsQuery'),
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='news_mapper_web.Source'),
        ),
    ]
