# Generated by Django 2.1.1 on 2018-09-26 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_article_url', models.URLField()),
                ('_author', models.CharField(max_length=75)),
                ('_date_published', models.DateTimeField()),
                ('_description', models.CharField(max_length=2500)),
                ('_image_url', models.URLField(blank=True, default=None, null=True)),
                ('_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_body', models.CharField(max_length=2500)),
                ('_date_published', models.DateTimeField(auto_now_add=True)),
                ('_date_last_edit', models.DateTimeField(auto_now_add=True)),
                ('_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(max_length=150)),
                ('_body', models.CharField(max_length=2500)),
                ('_date_published', models.DateTimeField(auto_now_add=True)),
                ('_date_last_edit', models.DateTimeField(auto_now_add=True)),
                ('_public', models.BooleanField(default=False)),
                ('_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_argument', models.CharField(max_length=500)),
                ('_choropleth', models.FileField(blank=True, default=None, null=True, upload_to='E:\\Alpha\\Software Development Capstone - 2905-01\\My Files\\Projects\\news_mapper_django\\app\\news_mapper_web/media/news_mapper_web/html/')),
                ('_choro_html', models.TextField(blank=True, max_length=200000)),
                ('_data', models.CharField(blank=True, max_length=200000)),
                ('_date_created', models.DateField(auto_now_add=True)),
                ('_date_range_end', models.DateField(blank=True, default=None, null=True)),
                ('_date_range_start', models.DateField(blank=True, default=None, null=True)),
                ('_filename', models.TextField(blank=True, max_length=700)),
                ('_filepath', models.TextField(blank=True, max_length=1000)),
                ('_public', models.BooleanField(default=False)),
                ('_query_type', models.CharField(choices=[('headlines', 'Headlines'), ('all', 'All')], default='all', max_length=50)),
                ('_archived', models.BooleanField(default=False)),
                ('_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_api_id', models.CharField(max_length=50)),
                ('_category', models.CharField(choices=[('businiess', 'Business'), ('entertainment', 'Entertainment'), ('general', 'General'), ('health', 'Health'), ('science', 'Science'), ('sports', 'Sports'), ('technology', 'Technology')], max_length=50)),
                ('_country', models.CharField(max_length=30)),
                ('_country_alpha_code', models.CharField(max_length=3)),
                ('_description', models.CharField(max_length=2000)),
                ('_language', models.CharField(max_length=50)),
                ('_name', models.CharField(max_length=250)),
                ('_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='_query',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='news_mapper_web.Query'),
        ),
        migrations.AddField(
            model_name='comment',
            name='_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='news_mapper_web.Post'),
        ),
        migrations.AddField(
            model_name='article',
            name='_query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='news_mapper_web.Query'),
        ),
        migrations.AddField(
            model_name='article',
            name='_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='news_mapper_web.Source'),
        ),
    ]
